services:
  db:
    image: postgis/postgis:16-3.4
    container_name: merida_dw
    environment:
      POSTGRES_DB: merida_dw
      POSTGRES_USER: merida
      POSTGRES_PASSWORD: merida123
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql:/sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U merida -d merida_dw"]
      interval: 5s
      retries: 10

volumes:
  pgdata:
